### ISSUE TITLE
AttributeError: 'module' object has no attribute 'group'

### ISSUE THREAD

**Issue by yswtrue** [theskumar/python-dotenv#71]
when I import dotenv the program crashed.

python version 2.7.13

```

Traceback (most recent call last):
  File "/home/ysw/Code/pyspark/main.py", line 5, in <module>
    from dotenv import load_dotenv, find_dotenv
  File "/home/ysw/.virtualenvs/spark/lib/python2.7/site-packages/dotenv/__init__.py", line 1, in <module>
    from .cli import get_cli_string
  File "/home/ysw/.virtualenvs/spark/lib/python2.7/site-packages/dotenv/cli.py", line 8, in <module>
    @click.group()
AttributeError: 'module' object has no attribute 'group'

```

These are my pip list:

```

astroid (1.5.3)
autopep8 (1.3.2)
backports.functools-lru-cache (1.4)
backports.shutil-get-terminal-size (1.0.0)
click (6.7)
configparser (3.5.0)
decorator (4.1.2)
enum34 (1.1.6)
ipython (5.4.1)
ipython-genutils (0.2.0)
isort (4.2.15)
lazy-object-proxy (1.3.1)
mccabe (0.6.1)
pathlib2 (2.3.0)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
py4j (0.10.4)
pycodestyle (2.3.1)
Pygments (2.2.0)
pylint (1.7.2)
pymongo (3.5.1)
PyMySQL (0.7.11)
pyspark (2.2.0)
python-dotenv (0.7.1)
scandir (1.5)
setuptools (36.2.7)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
SQLAlchemy (1.1.13)
traitlets (4.3.2)
wcwidth (0.1.7)
wheel (0.29.0)
wrapt (1.10.11)

```

**Comment by theskumar** [comment]
Hi @yswtrue , this seems like issue with click, can you try uninstalling `click` and installing it's version 5 if that helps.

```
pip uninstall click
pip install click==5.1.*
```

**Comment by yswtrue** [comment]
Hi @theskumar , I have tried this way, but it didn't work.
and I check the source code of click, there is the function in the module.

**Comment by pjona** [comment]
In my environment dotenv works with click 6.7.
You are sure you don't have in your project file called `click.py`?

**Comment by theskumar** [comment]
please open this if you still facing the issue. closing this right now.
