### ISSUE TITLE
Error when installing with Python 3.6

### ISSUE THREAD

**Issue by maxalbert** [theskumar/python-dotenv#53]
To reproduce (using a temporary environment set up with [`conda`](https://conda.io/)):
```bash
# Create temporary conda environment `tmpenv`
$ conda create --name tmpenv python=3.6
$ source activate tmpenv

# Try to install dotenv
$ pip install dotenv
# Error! See output below.

# Remove temporary conda environment
$ source deactivate tmpenv
$ conda remove --name tmpenv --all
```
The installation works fine with Python 3.5.

Here is the output of the `pip install dotenv` command.
```
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 156, in save_modules
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 196, in setup_context
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/__init__.py", line 2, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/extension.py", line 5, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/dist.py", line 7, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/command/__init__.py", line 8, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/command/install_scripts.py", line 3, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/pkg_resources.py", line 1518, in <module>
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/pip-build-il9z1kn9/dotenv/setup.py", line 23, in <module>
        scripts=['scripts/dotenv']
      File "~/miniconda3/envs/tmpenv/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 315, in __init__
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 361, in fetch_build_eggs
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 851, in resolve
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1123, in best_match
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1135, in obtain
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 428, in fetch_build_egg
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 664, in easy_install
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 694, in install_item
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 875, in install_eggs
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 1114, in build_and_install
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 1100, in run_setup
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 235, in run_setup
      File "~/miniconda3/envs/tmpenv/lib/python3.6/contextlib.py", line 82, in __enter__
        return next(self.gen)
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 197, in setup_context
      File "~/miniconda3/envs/tmpenv/lib/python3.6/contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 168, in save_modules
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 143, in resume
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/six.py", line 685, in reraise
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 156, in save_modules
      File "~/miniconda3/envs/tmpenv/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 196, in setup_context
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/__init__.py", line 2, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/extension.py", line 5, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/dist.py", line 7, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/command/__init__.py", line 8, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/setuptools/command/install_scripts.py", line 3, in <module>
      File "/private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/easy_install-no05k7m3/distribute-0.7.3/pkg_resources.py", line 1518, in <module>
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/b1/npl0095x3s96s_vfsb5_60d00000gq/T/pip-build-il9z1kn9/dotenv/
```

**Comment by maxalbert** [comment]
Sorry, I accidentally installed the wrong package (`dotenv` instead of `python-dotenv`). Whoops!

**Comment by johnyserpa** [comment]
Did the same thing too. Thanks :)

**Comment by mikeerickson** [comment]
Lolz, I did the same thing and was driving me nuts until I realized what I was doing.

**Comment by glmdev** [comment]
Yeah, this was helpful for me as well. :)

**Comment by PotatoMapper** [comment]
....Also Guilty of the same mistake... <(-.-<) Thank you for cataloging your screw up XD

**Comment by martinezhermes** [comment]
guilty...

**Comment by alexanderzx360** [comment]
same mistake, thx
